# Generated by Django 5.0.6 on 2024-07-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DollarExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=12600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Possessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('price_in_sum', models.IntegerField(blank=True, null=True)),
                ('price_in_dollar', models.IntegerField(blank=True, null=True)),
                ('total_in_sum', models.IntegerField(blank=True, null=True)),
                ('total_in_dollar', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.category')),
                ('dollar_exchange_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.dollarexchangerate')),
                ('given_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.currency')),
                ('possessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.possessor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
