# Generated by Django 5.0.6 on 2024-07-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_given_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='given_datetime',
            new_name='given_time',
        ),
    ]
